"""Updated Member model

Revision ID: 37bee8535727
Revises: 
Create Date: 2023-11-15 21:22:05.682602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37bee8535727'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.add_column('member', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('member', sa.Column('role', sa.String(length=100), nullable=False))
    op.drop_column('member', 'author')
    op.drop_column('member', 'title')
    op.drop_column('member', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('price', mysql.FLOAT(), nullable=True))
    op.add_column('member', sa.Column('title', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('member', sa.Column('author', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('member', 'role')
    op.drop_column('member', 'name')
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
